### ISSUE TITLE
1.0.3 failed to render YAML

### ISSUE THREAD

**Issue by ming-cui** [PKM-er/obsidian-zotero#130]
Just updated to 1.0.3 on Windows, and I got "failed to render YAML" error message when creating a new literature note. The settings were the same. What might cause this error? Thanks!

**Comment by ming-cui** [comment]
This might be caused by mapping `creators` or `authors` to YAML fields. That said, adding `creators` or `authors` on Template tab would cause `failed to render YAML`.

**Comment by MSBack** [comment]
I am also getting the same error.

Here's the error log in the Obsidian console:

```
plugin:obsidian-zotero-plugin:35 Error: Tag not resolved for Function value
    at app.js:1:643147
    at mm (app.js:1:643201)
    at Cm.toString (app.js:1:650384)
    at mm (app.js:1:642650)
    at app.js:1:645921
    at Array.reduce (<anonymous>)
    at Am._toString (app.js:1:645520)
    at Am.toString (app.js:1:654571)
    at mm (app.js:1:643588)
    at app.js:1:645921
$e @ plugin:obsidian-zotero-plugin:35
renderFrontmatter @ plugin:obsidian-zotero-plugin:236
renderNote @ plugin:obsidian-zotero-plugin:235
eval @ plugin:obsidian-zotero-plugin:250
createNoteForDocItem @ plugin:obsidian-zotero-plugin:250
createNoteForDocItemFull @ plugin:obsidian-zotero-plugin:250
```

And here's a slightly different version of the same error message. The first one was a bit shorter for some reason:

```
plugin:obsidian-zotero-plugin:35 Error: Tag not resolved for Function value
    at app.js:1:643147
    at mm (app.js:1:643201)
    at Cm.toString (app.js:1:650384)
    at mm (app.js:1:642650)
    at app.js:1:645921
    at Array.reduce (<anonymous>)
    at Am._toString (app.js:1:645520)
    at Am.toString (app.js:1:654571)
    at mm (app.js:1:643588)
    at app.js:1:645921
$e @ plugin:obsidian-zotero-plugin:35
renderFrontmatter @ plugin:obsidian-zotero-plugin:236
renderNote @ plugin:obsidian-zotero-plugin:235
eval @ plugin:obsidian-zotero-plugin:250
createNoteForDocItem @ plugin:obsidian-zotero-plugin:250
createNoteForDocItemFull @ plugin:obsidian-zotero-plugin:250
await in createNoteForDocItemFull (async)
xy @ plugin:obsidian-zotero-plugin:249
await in xy (async)
callback @ plugin:obsidian-zotero-plugin:250
bU @ app.js:1
e.executeCommand @ app.js:1
eval @ plugin:obsidian-kanban:77
o @ plugin:obsidian-kanban:23
eval @ plugin:ob-table-enhancer:1710
wrapper @ plugin:ob-table-enhancer:1535
e.executeCommandById @ app.js:1
eval @ plugin:obsidian-completr:80326
e.handleKey @ app.js:1
e.handleKey @ app.js:1
t.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
```


I also get this error simultaneously when creating a literature note:

```
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'path')
    at eval (plugin:obsidian-zotero-plugin:249:20099)
    at e.tryTrigger (app.js:1:957828)
    at e.trigger (app.js:1:957761)
    at t.trigger (app.js:1:1629950)
    at t.<anonymous> (app.js:1:1626283)
    at app.js:1:235927
    at Object.next (app.js:1:236032)
    at a (app.js:1:234750)
eval @ plugin:obsidian-zotero-plugin:249
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
setTimeout (async)
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
e.queue @ app.js:1
t.onCreateOrModify @ app.js:1
t.onCreate @ app.js:1
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
t.onChange @ app.js:1
e.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.reconcileFileCreation @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.reconcileFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.reconcileFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.reconcileInternalFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
n @ app.js:1
Promise.then (async)
e.queue @ app.js:1
e.write @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.create @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.createNewFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.createNewMarkdownFile @ app.js:1
createNoteForDocItem @ plugin:obsidian-zotero-plugin:250
createNoteForDocItemFull @ plugin:obsidian-zotero-plugin:250
await in createNoteForDocItemFull (async)
xy @ plugin:obsidian-zotero-plugin:249
await in xy (async)
callback @ plugin:obsidian-zotero-plugin:250
bU @ app.js:1
e.executeCommand @ app.js:1
eval @ plugin:obsidian-kanban:77
o @ plugin:obsidian-kanban:23
eval @ plugin:ob-table-enhancer:1710
wrapper @ plugin:ob-table-enhancer:1535
e.executeCommandById @ app.js:1
eval @ plugin:obsidian-completr:80326
e.handleKey @ app.js:1
e.handleKey @ app.js:1
t.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
```

And my debug info:
```
SYSTEM INFO:
	Obsidian version: v1.2.8
	Installer version: v1.2.8
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 11
	Restricted mode: off
	Plugins installed: 105
	Plugins enabled: 91
		1: Divide & Conquer v1.0.0
		2: Advanced new file v1.5.1
		3: Advanced Slides v1.20.0
		4: Advanced URI v1.35.0
		5: Auto Link Title v1.4.1
		6: Banners v1.3.3
		7: Better Word Count v0.9.6
		8: Buttons v0.4.19
		9: Calendar v1.5.10
		10: Commander v0.5.0
		11: Custom Frames v2.4.6
		12: Dataview v0.5.56
		13: Dictionary v2.22.0
		14: Emoji Shortcodes v2.2.0
		15: Excalidraw v1.9.1
		16: Force note view mode v1.1.1
		17: Gallery v0.5.8
		18: Hide Sidebars on Window Resize v1.1.0
		19: Hotkey Helper v0.3.17
		20: Hotkeys++ v0.2.7
		21: Inbox v1.1.0
		22: Kanban v1.5.3
		23: LanguageTool Integration v0.3.3
		24: Natural Language Dates v0.6.1
		25: Note Refactor v1.7.1
		26: Obsidian42 - BRAT v0.7.0
		27: Obsidian42 - Strange New Worlds (SNW) v1.2.2
		28: Obsidian42 - Text Transporter v1.0.3
		29: Pandoc Plugin v0.4.1
		30: Paste URL into selection v1.7.0
		31: Periodic Notes v0.0.17
		32: Prompt v1.1.0
		33: qmd as md v0.0.2
		34: Quick Explorer v0.2.8
		35: QuickAdd v1.0.2
		36: QuickShare v1.3.1
		37: Raindrop Highlights v0.0.17
		38: Reading Time v1.1.1
		39: Recent Files v1.3.5
		40: Review v1.6.4
		41: Smarter Markdown Hotkeys v1.16.4
		42: Sortable v0.3.1
		43: Spaced Repetition v1.10.1
		44: Style Settings v1.0.3
		45: Tag Wrangler v0.5.8
		46: Tasks v3.7.0
		47: Typewriter Scroll v0.2.2
		48: URI Commands v1.0.0
		49: Word Sprint v0.2.3
		50: Workbench v1.6.1
		51: Linter v1.14.0
		52: Update time on edit v1.1.2
		53: Templater v1.16.0
		54: Projects v1.15.3
		55: Cycle In Sidebar v1.0.2
		56: Emoji Toolbar v0.4.1
		57: Advanced Tables v0.18.1
		58: Table Enhancer v0.5.10
		59: Hover Editor v0.11.11
		60: Pandoc Reference List v1.2.11
		61: Create Note in Folder v0.0.9
		62: Plugin Groups v2.1.0
		63: Homepage v3.0.2
		64: Simple Day Planner v0.2.0
		65: Numerals v1.2.1
		66: Open vault in VSCode v1.2.1
		67: D2 v1.1.3
		68: Zotero Plugin v1.0.5
		69: Plugin Update Tracker v1.4.6
		70: Reminder v1.1.15
		71: File Diff v1.0.13
		72: Rollover Daily Todos v1.1.5
		73: Completr v3.1.3
		74: MetaEdit v1.8.0
		75: Gemmy v0.0.3
		76: Colorful Note Borders v0.2.4
		77: Supercharged Links v0.9.7
		78: Editor Syntax Highlight v0.1.3
		79: File Explorer Note Count v1.2.0
		80: Quiet Outline v0.3.15
		81: Readwise Official v2.0.1
		82: Enhancing Mindmap v0.2.4
		83: Home tab v1.1.2
		84: Obsidian Git v2.20.0
		85: Focus Mode v1.11.4
		86: Outliner v4.7.1
		87: Notion-Like Tables v6.9.3
		88: Settings Search v1.3.7
		89: Lapel v0.1.1
		90: Text Format v2.2.1
		91: Zotero Integration v2.3.9
```

**Comment by MSBack** [comment]
> This might be caused by mapping `creators` or `authors` to YAML fields. That said, adding `creators` or `authors` on Template tab would cause `failed to render YAML`.

I can confirm that I don't get this error, if I remove `authors` from my YAML mapping settings.

**Comment by MSBack** [comment]
Here is an error log generated with Log level set to "All" under the Misc settings:
```
0974d517-a743-4d27-8cd7-7fcc01900964:16 [2023-05-19T23:39:06.584] [DEBUG] obsidian-zotero:db-worker - Reading Zotero database for attachments of item 3081
0974d517-a743-4d27-8cd7-7fcc01900964:16 [2023-05-19T23:39:06.584] [DEBUG] obsidian-zotero:db-worker - Finished reading Zotero database for attachments of item 3081, count: 1
0974d517-a743-4d27-8cd7-7fcc01900964:16 [2023-05-19T23:39:06.585] [DEBUG] obsidian-zotero:db-worker - Reading Zotero database for tags
0974d517-a743-4d27-8cd7-7fcc01900964:16 [2023-05-19T23:39:06.586] [DEBUG] obsidian-zotero:db-worker - Finished reading Zotero database for tags
0974d517-a743-4d27-8cd7-7fcc01900964:16 [2023-05-19T23:39:06.586] [DEBUG] obsidian-zotero:db-worker - Reading Zotero database for annotations of attachment 9344
0974d517-a743-4d27-8cd7-7fcc01900964:16 [2023-05-19T23:39:06.589] [DEBUG] obsidian-zotero:db-worker - Finished reading Zotero database for annotations of attachment 9344, count: 1
0974d517-a743-4d27-8cd7-7fcc01900964:16 [2023-05-19T23:39:06.591] [DEBUG] obsidian-zotero:db-worker - Reading Zotero database for tags
0974d517-a743-4d27-8cd7-7fcc01900964:16 [2023-05-19T23:39:06.591] [DEBUG] obsidian-zotero:db-worker - Finished reading Zotero database for tags
plugin:obsidian-zotero-plugin:6 [2023-05-19T23:39:06.594] [WARN] obsidian-zotero:main - fileLink: file not found D:\User\Zotero\storage\JAVKTHRP\Acuna-Soto_et_al_2005_Drought,_epidemic_disease,_and_the_fall_of.pdf D:\User\Zotero\storage\JAVKTHRP\Acuna-Soto_et_al_2005_Drought,_epidemic_disease,_and_the_fall_of.pdf
plugin:obsidian-zotero-plugin:6 [2023-05-19T23:39:06.601] [ERROR] obsidian-zotero:main - Failed to renderYaml Tag not resolved for Function value <ref *1> {
  backlink: [Getter],
  fileLink: [Getter],
  authorsShort: [Getter],
  annotations: [
    {
      page: [Getter],
      backlink: [Getter],
      blockID: [Getter],
      commentMd: [Getter],
      imgPath: [Getter],
      imgUrl: [Getter],
      imgLink: [Getter],
      imgEmbed: [Getter],
      fileLink: [Getter],
      textBlock: [Getter],
      colorName: [Getter],
      docItem: [Circular *1]
    }
  ],
  creators: [
    { fullname: [Getter], toString: [Function: toString] },
    { fullname: [Getter], toString: [Function: toString] },
    { fullname: [Getter], toString: [Function: toString] },
    { fullname: [Getter], toString: [Function: toString] },
    { fullname: [Getter], toString: [Function: toString] }
  ],
  authors: [Getter]
} whitelist {
  title: true,
  citekey: true,
  year: true,
  DOI: 'doi',
  date: 'year',
  publicationTitle: 'publisher',
  authors: true
}
plugin:obsidian-zotero-plugin:35 Error: Tag not resolved for Function value
    at app.js:1:643147
    at mm (app.js:1:643201)
    at Cm.toString (app.js:1:650384)
    at mm (app.js:1:642650)
    at app.js:1:645921
    at Array.reduce (<anonymous>)
    at Am._toString (app.js:1:645520)
    at Am.toString (app.js:1:654571)
    at mm (app.js:1:643588)
    at app.js:1:645921
$e @ plugin:obsidian-zotero-plugin:35
renderFrontmatter @ plugin:obsidian-zotero-plugin:236
renderNote @ plugin:obsidian-zotero-plugin:235
eval @ plugin:obsidian-zotero-plugin:250
createNoteForDocItem @ plugin:obsidian-zotero-plugin:250
createNoteForDocItemFull @ plugin:obsidian-zotero-plugin:250
await in createNoteForDocItemFull (async)
xy @ plugin:obsidian-zotero-plugin:249
```

**Comment by zhechenghu** [comment]
This bug still exists in 1.0.5

**Comment by YIRU69** [comment]
Same bug in 1.0.6

**Comment by aidenlx** [comment]
Note Property now has a dedicated template in v1.1.0, which should fix this issue, make sure to check out [the document](https://obzt.aidenlx.top/getting-started/basic-usage/template-config#note-properties-template) on this changes and [cheatsheets](https://obzt.aidenlx.top/how-to/template-cheatsheet#authors)

**Comment by Rinnyboy** [comment]
Probably when editing the property in the zt-field.eta file， there is a space missing after “:”.
